name: flutter_sns_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  uuid: ^4.5.1
  intl: ^0.20.2
  firebase_storage: ^12.4.5
  tflite_flutter: ^0.11.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/splash.gif
