name: flutter_sns_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  sentry_flutter: ^8.14.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.13.0
  path_provider: ^2.1.5
  cloud_firestore: ^5.6.7
  uuid: ^4.5.1
  intl: ^0.20.2
  firebase_storage: ^12.4.5
  tflite_flutter: ^0.11.0
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.4.5
  go_router: ^15.1.2
  image_picker: ^1.1.2
  flutter_image_filters: ^0.0.26

dev_dependencies:
  sentry_dart_plugin: ^2.4.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/splash.gif

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter-sns-app
  org: 0624866916d0
